server:
  port: 7070
  servlet:
      session:
        timeout: 400s
  error:
    whitelabel:
      enabled: false


spring:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL93Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        current_session_context_class: thread
        jdbc:
          lob:
            non_contextual_creation: true


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/courses_db
    username: course_admin
    password: 123qwe
    driverClassName: org.postgresql.Driver
    initialization-mode: always



  jackson:
    serialization:
      fail-on-empty-beans: false



  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html


#  ###
#  #   H2 Settings
#  ###
#  h2:
#    console:
#      enabled: true
#      path: /h2


logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR